Add Contract Table / Share Modal
protofire/polkadot-contract-wizard pull request #217
Opened 2023-10-05 12:41 UTC by bogos

Add [Create "Contracts" table ](https://app.clickup.com/t/85ztqzmbc)
Add [Share contract Modal](https://app.clickup.com/t/85ztqzp2n)

2023-10-05 15:05 UTC, henrypalacios requested changes
Nice work, I like what you did with `DefaultToolTipButton` 🤝

I leave you some changes!

2023-10-05 15:05 UTC, henrypalacios commented on src/view/ContractView/ContractsTable/index.tsx
> +  const searchMetadata = async (codeId: string): Promise<string | void> => {
You are repeating this code that I have created, how about taking inspiration from the principle of segregation and extracting it to a hook to reuse it in both components?

2023-10-05 15:05 UTC, henrypalacios commented on src/view/ContractView/SearchInput.tsx
> +    console.log('value', event.target.value)
🕵️

2023-10-05 15:07 UTC, henrypalacios commented on src/pages/contracts/index.tsx
> +      <Typography variant="h1" align="left">
I just leave this comment: This made sense when there were only 2 different pages, now we have to think about creating a container layout for the pages. 

cc @alongoni

2023-10-05 15:51 UTC, bogos commented on src/view/ContractView/ContractsTable/ContractsTable.tsx
> +  Tooltip
DONE

2023-10-05 20:56 UTC, henrypalacios requested changes

2023-10-05 20:56 UTC, henrypalacios commented on src/view/ContractView/ContractsTable/ContractsTable.tsx
> +type ContractType = keyof typeof TITLE_MAP_TOKEN
why do you need to create this type, if it is already `contract.type` is a `TokenType`?

2023-10-05 20:56 UTC, henrypalacios commented on src/view/ContractView/ContractsTable/ContractsTable.tsx
> +          <TokenIconSvg label={contract.type as ContractType} />
As above, this Casting is unnecessary contract.type is already `TokenType`.

2023-10-05 21:25 UTC, bogos commented on src/view/ContractView/ContractsTable/ContractsTable.tsx
> +          <TokenIconSvg label={contract.type as ContractType} />
contract.type is ContractType

```
export type ContractType = TokenType | 'custom'
```
i need the cast only to TokenType for now since we don't have custom mode yet

2023-10-06 13:08 UTC, henrypalacios commented on src/constants/titleTokenType.ts
> +    imgPath: TOKEN_PATHS.psp37,
I will approve this PR, however, this image needs to be updated and the other contract types need to be verified.

cc @alongoni

2023-10-06 13:09 UTC, merged